#!/bin/sh

### BEGIN INIT INFO
# Provides:          corvex
# Required-Start:
# Required-Stop:
# Should-Stop:       
# X-Start-Before:
# Default-Start:     5
# Default-Stop:      0 1 6
# Short-Description: Start / stop corvex daemons
# Description:       
### END INIT INFO

set -e

# Include core init functions if needed
. /lib/lsb/init-functions

PARAM=/var/www/html/scripts/tools/config.sh
if [ -f $PARAM ]; then
    . "$PARAM"
fi

case "${1:-}" in
  stop|reload|restart|force-reload)
        echo "Stopping corvex services."
        ;;

  start)
        echo "Starting corvex services."
        /home/corvex/tunnel.sh &
        /var/www/html/scripts/tools/ipForwarding.sh
        /var/www/html/scripts/tools/scanUploads.sh $watchdir &
        ;;

  *)
        echo "Usage: ${0:-} {start|stop|status|restart|reload|force-reload}" >&2
        exit 1
        ;;
esac
